import {
  Beat,
  Collection,
  FreeDownloadLead,
  ProducerProfile,
  Promotion,
  SaleRecord,
  StoreSettings,
  BeatPack,
} from '../types';

export const INITIAL_PRODUCER_PROFILE: ProducerProfile = {
  name: 'CASHMERE KID$',
  handle: '@cashmerekid',
  avatarUrl: '/src/assets/images/cashmere_cover_velvet_1790419833792.jpg',
  bannerUrl: '/src/assets/images/cashmere_hero_runway_1790419818906.jpg',
  bio: 'Multi-Platinum & Grammy-Nominated Audio Architect crafting luxury instrumentals for world-tier recording artists. Beats built for the next era.',
  verified: true,
  location: 'Atlanta / Los Angeles / Tokyo',
  socialLinks: {
    youtube: 'https://youtube.com',
    instagram: 'https://instagram.com',
    spotify: 'https://spotify.com',
    twitter: 'https://twitter.com',
    soundcloud: 'https://soundcloud.com',
  },
};

export const INITIAL_COLLECTIONS: Collection[] = [
  {
    id: 'col-runway',
    name: 'THE RUNWAY COLLECTION',
    description: 'Ultra-exclusive trap & dark synth compositions tailored for high-fashion runway shows and international campaigns.',
    artworkUrl: '/src/assets/images/cashmere_hero_runway_1790419818906.jpg',
    beatCount: 4,
    createdDate: '2026-03-01',
  },
  {
    id: 'col-obsidian',
    name: 'THE OBSIDIAN VAULT',
    description: 'Heavy 808s, analog modular synth basslines, and hypnotic atmospheric pads engineered for multi-platinum vocalists.',
    artworkUrl: '/src/assets/images/cashmere_cover_vault_1790419848357.jpg',
    beatCount: 3,
    createdDate: '2026-03-10',
  },
];

export const INITIAL_BEATS: Beat[] = [
  {
    id: 'beat-obsidian-runway',
    title: 'OBSIDIAN RUNWAY',
    producerName: 'CASHMERE KID$',
    bpm: 140,
    key: 'F# Minor',
    duration: '2:45',
    durationSeconds: 165,
    pricing: {
      mp3Lease: 39.99,
      premiumLease: 79.99,
      unlimited: 249.99,
      exclusive: 1200.0,
    },
    freeDownload: true,
    freeDownloadType: 'email_required',
    genre: 'TRAP',
    subGenres: ['Dark Trap', 'Luxury Trap', '808 Heavy'],
    moods: ['Dark', 'Aggressive', 'Hypnotic', 'Expensive'],
    tags: ['voodoo', 'darktrap', 'cashmere', 'platinum', '808'],
    artworkUrl: '/src/assets/images/voodoo_cover_obsidian_1790419259195.jpg',
    audioUrl: '/media/as_aud_1790611891771.mp3',
    playCount: 4280,
    downloadCount: 512,
    likeCount: 384,
    collectionId: 'col-runway',
    featured: true,
    published: true,
    releaseDate: '2026-03-15',
    description: 'Dark, brooding analog synthesizers collide with devastating 808 glides and crisp percussion.',
    voiceTag: true,
    isNew: true,
  },
  {
    id: 'beat-velvet-vault',
    title: 'VELVET VAULT',
    producerName: 'CASHMERE KID$',
    bpm: 144,
    key: 'C# Minor',
    duration: '3:10',
    durationSeconds: 190,
    pricing: {
      mp3Lease: 39.99,
      premiumLease: 79.99,
      unlimited: 249.99,
      exclusive: 1200.0,
    },
    freeDownload: false,
    genre: 'DARK SYNTH',
    subGenres: ['Synthwave', 'Dark Ambient', 'Cinematic'],
    moods: ['Ethereal', 'Luxury', 'Moody'],
    tags: ['velvet', 'vault', 'cashmere', 'analog', 'synth'],
    artworkUrl: '/src/assets/images/cashmere_cover_velvet_1790419833792.jpg',
    audioUrl: '/media/as_aud_1790611891771.mp3',
    playCount: 3820,
    downloadCount: 290,
    likeCount: 245,
    collectionId: 'col-obsidian',
    featured: true,
    published: true,
    releaseDate: '2026-03-20',
    description: 'Vintage analog synth textures, wide stereo pads, and punchy modern drums designed for billboard records.',
    voiceTag: true,
    isNew: true,
  },
  {
    id: 'beat-platinum-runway',
    title: 'PLATINUM RUNWAY',
    producerName: 'CASHMERE KID$',
    bpm: 138,
    key: 'D Minor',
    duration: '2:52',
    durationSeconds: 172,
    pricing: {
      mp3Lease: 49.99,
      premiumLease: 99.99,
      unlimited: 299.99,
      exclusive: 1500.0,
    },
    freeDownload: true,
    freeDownloadType: 'tagged',
    genre: 'FREESTYLE TRAP',
    subGenres: ['Atlanta Trap', 'Bouncy', 'Club'],
    moods: ['Energetic', 'Confident', 'Bouncy'],
    tags: ['platinum', 'runway', 'cashmere', 'freestyle', 'hit'],
    artworkUrl: '/src/assets/images/beat_artwork_platinum_1790418694282.jpg',
    audioUrl: '/media/as_aud_1790611914775.m4a',
    playCount: 5120,
    downloadCount: 780,
    likeCount: 620,
    collectionId: 'col-runway',
    featured: true,
    published: true,
    releaseDate: '2026-03-22',
    description: 'Bouncy, infectious rhythm with crisp rolling hi-hats and a punchy low-end tailored for dynamic lyrical flows.',
    voiceTag: true,
    isNew: true,
  },
  {
    id: 'beat-dark-synthesis',
    title: 'DARK SYNTHESIS',
    producerName: 'CASHMERE KID$',
    bpm: 142,
    key: 'A Minor',
    duration: '3:05',
    durationSeconds: 185,
    pricing: {
      mp3Lease: 39.99,
      premiumLease: 79.99,
      unlimited: 249.99,
      exclusive: 1200.0,
    },
    freeDownload: false,
    genre: 'HARD TRAP',
    subGenres: ['Rage', 'Dark Trap', 'Heavy Bass'],
    moods: ['Aggressive', 'Hype', 'Dark'],
    tags: ['darksynth', 'hard', 'distortion', '808'],
    artworkUrl: '/src/assets/images/beat_artwork_darktrap_1790418703946.jpg',
    audioUrl: '/media/as_aud_1790612890896.mp3',
    playCount: 4690,
    downloadCount: 410,
    likeCount: 390,
    featured: true,
    published: true,
    releaseDate: '2026-03-25',
    description: 'Distorted 808s, haunting minor melodies, and razor-sharp percussion for an unmistakable hard trap vibe.',
    voiceTag: true,
    isNew: false,
  },
];

export const INITIAL_PROMOTIONS: Promotion[] = [
  {
    id: 'promo-1',
    code: 'CASHMERE50',
    discountPercent: 50,
    active: true,
    usageCount: 0,
    expirationDate: '2026-12-31',
    description: '50% OFF All Non-Exclusive Leases for VIP Artist Members',
  },
];

// Clean zero-state arrays for real transaction history (NO fake sales or fake customers!)
export const INITIAL_SALES_RECORDS: SaleRecord[] = [];
export const INITIAL_FREE_DOWNLOAD_LEADS: FreeDownloadLead[] = [];

export const INITIAL_STORE_SETTINGS: StoreSettings = {
  currency: 'USD',
  currencySymbol: '$',
  storeName: 'CASHMERE KID$',
  customDomain: 'cashmerekid.com',
  stripeConnected: true,
  paypalConnected: false,
  requireEmailForFreeDownload: true,
  voiceTagFrequencySeconds: 15,
  autoSendInvoices: true,
};

export const INITIAL_BEAT_PACKS: BeatPack[] = [
  {
    id: 'pack-platinum-vault',
    name: 'CASHMERE PLATINUM VAULT BUNDLE',
    description: 'All 4 luxury chart-ready trap & dark synth masters bundled with full WAV stems and commercial release contracts.',
    artworkUrl: '/src/assets/images/cashmere_hero_runway_1790419818906.jpg',
    beatIds: [
      'beat-obsidian-runway',
      'beat-velvet-vault',
      'beat-platinum-runway',
      'beat-dark-synthesis',
    ],
    price: 99.99,
    freeDownload: false,
    published: true,
    createdDate: '2026-03-25',
  },
];
